// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type SignUpRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   string `json:"gender,options=male|female|secret,default=secret"`
}

type SignUpResponse struct {
	Message string `json:"message"`
}
