// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeBat() bat {
	mainAnimal := newAnimal()
	mainMouse := newMouse(mainAnimal)
	mainFlyer := newFlyer(mainAnimal)
	mainBat := newBat(mainMouse, mainFlyer)
	return mainBat
}
