// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: greet.proto

package server

import (
	"context"

	"github.com/cylixlee/go-framework-playground/internal/logic/greet"
	"github.com/cylixlee/go-framework-playground/internal/proto"
	"github.com/cylixlee/go-framework-playground/internal/svc"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

func (s *GreetServer) Ping(ctx context.Context, in *proto.GreetRequest) (*proto.GreetResponse, error) {
	l := greetlogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
