// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: hello.proto

package server

import (
	"context"

	"github.com/cylixlee/go-framework-playground/internal/logic/hello"
	"github.com/cylixlee/go-framework-playground/internal/proto"
	"github.com/cylixlee/go-framework-playground/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) Ping(ctx context.Context, in *proto.HelloRequest) (*proto.HelloResponse, error) {
	l := hellologic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
